### PR TITLE
adapt the code to use the new MonadFail class

### PR DESCRIPTION
**Pull request by peti**
This change fixes https://github.com/silkapp/multipart/issues/3.

### CODE REVIEW

**Comment by hesselink** [comment]
LGTM, thanks! Tested on 8.6 and 8.8.

**Comment by hesselink** [comment]
Released to hackage: http://hackage.haskell.org/package/multipart-0.2.0

**Comment by peti** [comment]
Thank you very much.

**Comment by peti** [comment]
Oh, BTW, it might be worthwhile to edit the older release to constrain `base < 4.13`, since they do not compile with new versions. Without that information, `cabal-install` is possibly going to construct invalid build plans.

**Comment by hesselink** [comment]
Good idea, done!

**Pull request merged**
